### ISSUE TITLE
Personal data processed

### ISSUE THREAD

**Issue by nemobis** [KwnyPwny/cvecrowd.com#7]
On https://cvecrowd.com/privacy-policy, thanks for not requiring cookies. A couple sentences could be made clearer:

> This website does not use cookies of any kind. It does not contain forms or other mechanisms that process personal data.

This is negated by the next sentence which says there are in fact access logs with personal data (IP address and user agent). Also, the fediverse posts themselves are displayed with names and avatars which are most likely personal data.

> The web server stores log files for technical and operational reasons and the preparation of access statistics.

It would be nice to mention how long the logs are kept.

**Comment by KwnyPwny** [comment]
Thanks for reaching out. 

> On https://cvecrowd.com/privacy-policy, thanks for not requiring cookies. A couple sentences could be made clearer:
> 
> > This website does not use cookies of any kind. It does not contain forms or other mechanisms that process personal data.
> 
> This is negated by the next sentence which says there are in fact access logs with personal data (IP address and user agent). 

Since there are no user accounts, tracking cookies or similar, I do not consider these log files to be personal.

> Also, the fediverse posts themselves are displayed with names and avatars which are most likely personal data.

I am referring to personal data of **users / visitors** of the website.

> It would be nice to mention how long the logs are kept.

Currently 14 days. However, I am not sure whether this sufficies or if I should increase that value.


I'll think about clarifying the sentences accordingly.

**Comment by KwnyPwny** [comment]
I just updated the privacy policy to clarify your points.
